
#INSTALLATION OF THE JDK
FROM openjdk:17

WORKDIR /app

LABEL authors="shethiad"

#PLACEMENT OF THE EXECUTABLE [MICROSERVICE] ON THE IMAGE
COPY target/eureka-server-0.0.1.jar eureka-server-0.0.1.jar

#EXPOSE PORTS FOR INCOMING TRAFFIC - HOST_PORT:CONTAINER_PORT
EXPOSE 8761:8761

#ENTRYPOINT OF THE CONTAINER THROUGH THE MICROSERVICE
ENTRYPOINT ["java","-jar","eureka-server-0.0.1.jar"]